version: '3.8'

services:
  biliskilke:
    build:
      context: .
      target: prod
    volumes:
      - .:/app:consistent
    ports:
      - '7100:7100'

networks:
  default:
    external:
      name: prodeko-docker-net
