# Generated by Django 3.2.10 on 2021-12-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("elo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fargo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("favorite_color", models.IntegerField(default=16711680)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winner_elo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("winner_fargo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("loser_elo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("loser_fargo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("datetime", models.DateTimeField()),
                ("under_table", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "loser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_games",
                        to="bilis.player",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_games",
                        to="bilis.player",
                    ),
                ),
            ],
        ),
    ]
